# Generated by Django 5.2.14 on 2026-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=50)),
                ("records_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(max_length=20)),
                ("error_msg", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
