# Generated by Django 5.2.14 on 2026-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id_ext", models.CharField(max_length=64)),
                ("photo", models.ImageField(blank=True, upload_to="proofs/")),
                ("signature", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id_ext", models.CharField(max_length=64)),
                ("order_ref", models.CharField(db_index=True, max_length=100)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
