# Generated by Django 5.2.14 on 2026-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytracking",
            name="driver_first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
